version: '3'

services:
  web:
    build: .
    container_name: web-server
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my-network
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3366:3306"
    environment:
      MYSQL_USER: agent
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: apmsetup
    restart: always
    volumes:
       - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
